spring:
  freemarker:
    suffix: .html
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webjpa
logging:
  level:
    sql: debug
    web: debug
mybatis:
  mapper-locations: classpath:mapper/*
