spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webdemo?serverTimezone=Asia/Shanghai
    #spring:
    #  datasource:
    #    url: jdbc:postgresql://127.0.0.1:5432/demo
    #    driver-class-name: org.postgresql.Driver
    #    username: postgres
    #    password: root
hengboy:
  enhance:
    mapper-locations:
  pageable:
    dialect: mysql
