spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webjpa?serverTimezone=Asia/Shanghai
logging:
  level:
    sql: debug
    web: debug
    com.yuan.springbootwebmybatis.mapper.UserMapper: debug
mybatis:
  mapper-locations: classpath:mapper/*
  configuration:
    default-executor-type: batch
    cache-enabled: true
